<section class="page-header">
  
    <h5 class="page-title">Terms & Policy</h5>
  
</section>
<section>
  <div class="container">
    <p>By this privacy policy, we are committed to protecting the privacy of internet users. This policy explains our policy regarding the collection, use, disclosure and transfer of your information by us i.e. cgwebnews.in, which is a unit of cgwebnews.in or its subsidiary (ies) and or affiliate(s) (collectively referred to as the 'Company').</p>
            <p>It is a websites and performs other services including, but not limited to, the delivery of information and content via any mobile or internet-connected device or otherwise (collectively the ‘Services'). </p>
            <h5>GENERAL</h5>
            <p>This statement refers to practices on cgwebnews.in. The Company respects the privacy of the users of the Services and is committed to reasonably protect it. The information about the user, as collected by the Company is: (a) information supplied by users and (b) information automatically tracked while navigation (c) information collected from any other source (collectively referred to as ‘information').</p>
            <h5>RELATIONSHIP</h5>
            <p>cgwebnews.in is a unit of Rajasthan Patrika Pvt. Ltd., therefore, all administration and management issues are undertaken by cgwebnews.in</p>
            <h5>COLLECTION OF INFORMATION</h5>
            <p>cgwebnews.in and our service providers collect the following information from and about you.</p>
            <h5>REGISTRATION INFORMATION</h5>
            <p>The information - name, sex, age, address, pin code, contact number, occupation, interests and email address etc. - that you submit to register for Patrika,com Service, to create an account, post comments, receive a newsletter, or enter a contest or sweepstakes is called Registration Information.
            </p>
            <h5>PUBLIC INFORMATION AND POSTS</h5>
            <p>These consist of comments or content that you post to cgwebnews.in. This may include a name, user name, comments, likes, status, profile information and picture. Public information and posts are always public, which means they are available to everyone and may be displayed in search results on external search engines.</p>
            <h5>VOLUNTARY INFORMATION</h5>
            <p>We may collect additional information when you provide feedback, change your content or email preferences, respond to a survey, or communicate with us.</p>
            <h5>SUBSCRIPTION OR PAID SERVICE DATA</h5>
            <p>When you choose any subscription or paid service, we, or our payment gateway provider, may collect your purchase address or billing information, including your credit card number and expiration date, etc. However, when you order using an in-app purchase option, the same is handled by the platform providers. The subscriptions or paid Services may be on auto renewal mode, unless cancelled. If at any point you do not wish to auto-renew your subscription, you may cancel your subscription before the end of the subscription term. </p>
            <h5>INFORMATION FROM OTHER SOURCES</h5>
            <p>We may receive information about you from other sources, add it to our account information and treat it in accordance with this policy. If you provide information to the platform provider or another partner, whom we provide services, your account information and order information may be passed on to us. We may obtain updated contact information from third parties in order to correct our records and provide Services or communicate with you.</p>
            <h5>DEMOGRAPHIC AND PURCHASE INFORMATION</h5>
            <p>We may refer to other sources of information to provide you with targeted communications and promotions. We use Google Analytics, among others, to track user behaviour on our Website. Google Analytics has been enabled to support display advertising and help us understand our users' demographics and interests. </p>
            <p>The reports are anonymous and cannot be associated with any individual or personallyidentifiable information that you may have shared with us. You can opt-out of Google Analytics for display advertising and customise Google Display Network ads using the Ads Settings options provided by Google. </p>
            <h5>COOKIES</h5>
            <p>To enhance the responsiveness of the application and to enhance your experience on our Services, we may place 'cookies', or similar electronic tools on your computer or device. Cookies are small text files that collect information to assign each visitor a unique, random number as a user identification (User ID), to understand the user's individual interests. Cookies do not tell us your e-mail address or other personal information unless you voluntarily choose to give the information to us by registering on one of our services. The only personal information a cookie can contain is information you supply. A cookie cannot read data from your hard drive.</p>
            <p>Our advertisers may also assign their own cookies to your browser (if you click on their ads), a process that we do not control. Most browsers automatically accept cookies but you can set your browser option so that you will not receive cookies and you can also delete existing cookies from your browser.</p>
            <h5>OPTING OUT</h5>
            <p>If a user opts out using the Ads Settings, the unique Double Click cookie ID on the user's browser is overwritten with the phrase 'OPT_OUT'. Because there is no longer a unique cookie ID, the opt-out cookie can't be associated with a particular browser. </p>
            <h5>LOG FILE INFORMATION</h5>
            <p>We automatically collect information, though limited, about your computer's connection to the internet, mobile number, including your IP address, when you visit our Website, Application or Service. Your IP address is a number that lets computers attached to the internet know where to send your data - such as the pages you view. We automatically receive and log information from your browser, including your IP address, your computer's name, your operating system, browser type and version, CPU speed and connection speed. We may also collect log information from your device, including your location, IP address, your device's name, device's serial number or unique identification number (e.g. UDiD on your iOS device), your device operating system, browser type and version, CPU speed, and connection speed etc. </p>
            <h5>EXTERNAL LINKS</h5>
            <p>This Website contains links to other websites. We, Rajasthan Patrika Pvt. Ltd. or Patrika News, are not responsible for the privacy practices or the content of any such website or links.</p>
            <h5>CLEAR GIFS</h5>
            <p>We may user 'clear GIFs' (web beacons) to track the online usage patterns of our users in an anonymous manner, without personally identifying the user. We may also use clear GIFs in HTML-based emails sent to our users to track which emails are opened by recipients. We use this information to inter-alia deliver our web pages to you, to tailor our Website, Application or Service to the interests of our users, to measure traffic within our Application, to improve the application quality, functionality and interactivity and let advertisers know the geographic locations of our visitors. </p>
            <h5>LINKS TO THIRD PARTY WEBSITES / AD-SERVERS</h5>
            <p>The Application may include links to other websites or applications. Such websites or applications are governed by their respective privacy policies, which are beyond our control. Once you leave our servers (you can tell where you are by checking the URL in the location bar on your browser), use of any information you provide is governed by the privacy policy of the application you are visiting. That policy may differ from ours. If you can't find the privacy policy of these websites via a link from the application's homepage, you should contact the application owners. </p>
            <p>When we present information to our advertisers, it is usually in the form of aggregated statistics on traffic to various pages or content within our Websites or Applications. We use third-party advertising companies to serve ads when you visit our Websites or Applications. These companies may use information (not including your name, address, email address or telephone number or other personally identifiable information) about your visits to this and other websites or application, in order to provide advertisements about goods and services of interest to you. We do not provide any personally identifiable information to third party websites, advertisers or ad-servers without your consent. </p>
            <h5>INFORMATION USE BY THE COMPANY</h5>
            <p>The information supplied by the users enables us to improve the Services and provide you with a user-friendly experience. In some cases/provision of certain service(s) or utility(ies), we may require your contact address as well. All required information is service-dependent and the Company may use the above user information to, maintain, protect, and improve the Services (including advertising on the Application) and for developing new services. We may also use your email address or other personally identifiable information to send commercial or marketing messages without your consent, with an option to subscribe or unsubscribe, where feasible. We may, however, use your email address without further consent for non-marketing or administrative purposes (such as notifying you of major changes, for customer service purposes, billing, etc.). </p>
            <p>Any personally identifiable information provided by you will not be considered as sensitive if it is freely available and/or accessible in the public domain like any comments, messages, blogs, scribbles available on social platforms like Facebook, Twitter etc. </p>
            <p>Any information posted, uploaded, conveyed, communicated by users on the public sections of the Application becomes published content and is not considered personally identifiable information, subject to this Privacy Policy. </p>
            <p>In case you decline to submit personally identifiable information on the Application, we may not be able to provide certain services on the Application. We will make reasonable efforts to notify you of the same at the time of opening your account. In any case we will not be liable and or responsible for the denial of certain Services to you in case you do not provide the necessary information. </p>
            <p>When you register with the Application or Services, we may contact you about updation of your personal information to provide features that we believe may benefit or interest you.</p>
            <h5>INFORMATION SHARING</h5>
            <p>The Company shares your information with third parties without obtaining the prior consent of the user in the following circumstances: </p>
            <p>a) When it is requested or required by law, by court, a governmental agency or authority to disclose, for the purpose of verification of identity, or for the prevention, detection, investigation including cyber incidents, or for prosecution and punishment of offences. These disclosures are made only when a disclosure is reasonably necessary for enforcing these terms or for complying with laws and regulations. </p>
            <p>b) The Company proposes to share such information within its group companies, and with officials and employees of group companies, for the purpose of processing personal information on its behalf. We also ensure that the recipients of such information agree to process such information based on our instructions and in compliance with this Privacy Policy and other appropriate confidentiality and security measures.</p>
            <p>c) The Company may present information to our advertisers - to help them understand our audience and confirm the value of advertising on our Websites or Applications. However, it is usually in the form of aggregated statistics on traffic to various pages within our Website.</p>
            <p>d) The Company may share your information regarding your activities on Websites or Applications with third party social websites to populate your social wall that is visible to other people. However, you will have an option to set your privacy settings where you can decide what you want to share with others.</p>
            <h5>OUR COMMITMENT TO SECURITY</h5>
            <p>We have put in place appropriate administrative, technical, and physical safeguards to prevent unauthorized access, maintain data security and correctly use the information that we collect. No system can be completely secure, however, and we do not guarantee that unauthorised disclosures and access will not happen.</p>
            <h5>ACCESSING, CORRECTING, AND DELETING YOUR PERSONAL INFORMATION</h5>
            <p>We will take reasonable steps to accurately record the personal information that you provide to us and any subsequent updates.</p>
            <p>We encourage you to review, update, and correct the personal information that we maintain about you, and you may request us to delete your personal information that is inaccurate, incomplete, or irrelevant for legitimate purposes, or is being processed in a way which infringes any applicable legal requirements, by contacting us as given in the 'How to Contact Us' section mentioned below.</p>
            <p>We may choose to retain the information with your comments or corrections in our records. By contacting us, you may also object to our further use of your personal information if you have compelling legitimate grounds, which may involve closing your account. We may ask you to verify your identity and to provide other details before we are able to provide you with any information, correct any inaccuracies, or delete any information.</p>
            <p>Your right to review, update, correct, and delete your personal information may be limited,subject to the law or your jurisdiction: (i) if your requests are abusive or unreasonably excessive, (ii) where the rights or safety of another person, or persons, would be encroached upon, or (iii) if the information you request, relates to existing or anticipated legal proceedings between you and us, or providing access to you would prejudice negotiations between us or an investigation of possible unlawful activity. Your right to review, update, correct and delete your information is subject to our records, retention policies and applicable law, including any statutory retention requirements.
            </p>
            <h5>Third Party Data Policy</h5>
            <p>i. This app contains a software development kit (“SDK”) from a third party, Red Brick Lane Marketing Solutions Private Limited (“RBL”). The SDK is integrated with this app for the purposes of profiling the device on media consumption and other device data and utilizing the same to target relevant content and ads to the device (“Services”) pursuant to the terms and conditions of RBL Services (“Terms of Use”). Further details can be obtained at <a target="_blank" href="http://www.zapr.in/privacy/">http://www.zapr.in/privacy/</a>.</p>
            <p>ii. If you do not wish for RBL to identify television, radio and other offline content viewing around your mobile device, please opt out of all RBL Services via the following link: <a target="_blank" href="http://www.zapr.in/privacy/">http://www.zapr.in/privacy/</a>.</p>
            <p>iii. RBL does not collect any personally identifiable information or audio/video / image/contact files from your mobile device. For any questions or clarifications please reach out to: <a href="/cdn-cgi/l/email-protection#96e6e4ffe0f7f5efd6ecf7e6e4b8fff8" target="_blank"><span class="__cf_email__" data-cfemail="fe8e8c97889f9d87be849f8e8cd09790">[email&#160;protected]</span></a>.</p>
            <p>iv. RBL also automatically receives and tracks certain data about your mobile device (such as your device-type, installed software and language preference) or desktop interface, your taps and interests; and may create a unique device or user ID for you. In some cases RBL can automatically detect or infer your location using GPS, your IP address, watermarks and/or Bluetooth, but often your operating system will require you to grant RBL permission to access your GPS or Bluetooth settings; please refer to your device’s system settings regarding location services.</p>
            <h5>RETENTION OF PERSONAL INFORMATION</h5>
            <p>We will retain your personal information while you have an account with us, and thereafter for as long as we need it, for purposes not prohibited by law. Thereafter, we will either delete your personal information or de-identify it so that it is anonymous and not attributed to you. Your rights to request that we delete your personal information are set forth in the 'Accessing, Correcting, and Deleting Your Personal Information' section above.</p>
            <h5>CHANGES TO THIS PRIVACY POLICY</h5>
            <p>This Privacy Policy may be changed by the Company. The revised Privacy Policy will be posted on this page for your understanding and use of how we collect and use information.</p>
            <h5>HOW TO CONTACT US</h5>
            <p>If you have questions about this Privacy Policy, please contact us at:- www.cgwebnews.in</p>
            <h4>Copyright</h4>
            <p>Copyright © 2017 cgwebnews.in
              <br> All rights reserved.
              <br> Our company website is protected by copyright law through Copyright © 2017, cgwebnews.in, and its affiliated or related companies. The copyright for specific content such as articles, photos and images rests with their respective owners. All rights reserved.</p>
            <h4>Unauthorised distribution, transmission or publication is strictly prohibited.</h4>
            <p>Materials on this website belong to respective owners who have produced such materials and are protected by national and international intellectual property laws, conventions and treaties. Therefore, they may only be used for your personal non-commercial purposes, single copy only. The company and or the respective copyright owners may undertake legal action in case of infringement of these rights.</p>
            <p>All other rights are reserved, and commercial use including publication, re-transmission, broadcast, posting to newsgroups, mail lists or electronic bulletin boards, circulation, selling, reproduction or redistribution in any medium(s) are prohibited, except with the prior written approval of the copyright owner(s).</p>
            <h4>For further information, or to request permission to re-publish, contact:</h4>
            <p>e-mail: admin@cgwebnews.in</p>
            <p>Disclaimer:- The information in this web-site and any attachments is confidential and may be legally privileged. It is intended solely for the user. If you are not an intended recipient, please delete the message and any attachments and notify the sender of mis-delivery. Any use or disclosure of the contents of either is unauthorized and may be unlawful. All liability for viruses is excluded to the fullest extent permitted by law. Any views expressed in this web site are those of the individual sender, except where the sender states them, with requisite authority, to be those of the organization. cgwebnews.in is not responsible for any unauthorized and unlawful use of the web site by any third person against any other person.</p>
            <h5>GRIEVANCE SOLUTION</h5>
            <p>Any complaints made with regards to the contents of web site or the information provided by any third party or breach of the terms shall be immediately informed to the designated Grievance Officer as mentioned below in writing or through email with sufficient id proof to <a href="/cdn-cgi/l/email-protection#11777474757370727a51787f3f61706563787a703f727e7c" target="_blank"><span class="__cf_email__" data-cfemail="e1878484858380828aa1888fcf91809593888a80cf828e8c">[email&#160;protected]</span></a> </p>
            <p>The complaint is made in the following format:-</p>
            <p>a) Identification of the information provided by you;</p>
            <p>b) Clear statement as to whether the information is personal information or sensitive personal information;</p>
            <p>c) Your address, telephone number or e-mail address;</p>
            <p>d) A statement that you have a good-faith belief that the information has been processed incorrectly or disclosed without authorization, as the case may be;</p>
            <p>e) A statement, under penalty of perjury, that the information in the notice is accurate, and that the information being complained about belongs to you;</p>
            <p>f) You may also contact us in case you have any questions / suggestions about the Privacy Policy using the contact information mentioned above.</p>
            <p>The website /company will not responsible for any communication, if addressed, to any nondesignated person in this regard.</p>
  </div>
</section>